In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [4]:
#define tensor
tensor = tf.constant([[23,4],[32,51]])

In [5]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [6]:
tensor.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [7]:
#getting value in constant
session = tf.Session()

In [8]:
session.run(tf.global_variables_initializer())

In [11]:
tensor_value = session.run(tensor)

In [12]:
tensor_value

array([[23,  4],
       [32, 51]])

In [13]:
variable = tf.Variable([[30,20],[10,45]])

In [14]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [15]:
variable.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [16]:
#getting value in variable
session = tf.Session()

In [17]:
session.run(tf.global_variables_initializer())

In [18]:
tensor_value = session.run(variable)

In [19]:
tensor_value

array([[30, 20],
       [10, 45]])

In [20]:
variable.eval(session)

array([[30, 20],
       [10, 45]])