In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
import numpy as np

In [4]:
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [6]:
tensor_20.shape

TensorShape([2, 2])

In [7]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [8]:
numpy_tensor = np.array([[23,  4], [32, 51]])

In [9]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [11]:
tf2_variable = tf.Variable([[1.,2.,3.], [4.,5.,6.]])

In [12]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [13]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [14]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>