In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]

In [3]:
my_list

[1, 2, 3, 4]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3, 4])

In [6]:
my_lits = [[1,2,3],[3,4,5],[6,7,8]]

In [9]:
my_array =np.array( [my_lits])

In [10]:
my_array

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.arange(0,11,2)

In [14]:
arr

array([ 0,  2,  4,  6,  8, 10])